choco install -y 7zip.install
choco install -y autohotkey.install
choco install -y notepad2-mod
#choco install -y sublimetext3
choco install -y f.lux
choco install -y zoomit
choco install -y googlechrome 
choco install -y sysinternals
choco install -y paint.net
#choco install -y kindle
#choco install -y skype
choco install -y discord
#choco install -y webpi